version: '3'

services:
  # Enable Prometheus plugin: rabbitmq-plugins enable rabbitmq_prometheus
  # Check :15692/metrics for metrics.
  rabbitmq:
    image: docker.io/rabbitmq:management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "15692:15692"   # RabbitMQ management console
      - "15672:15672"   # RabbitMQ management console
      - "5672:5672"     # RabbitMQ messaging
    networks:
      - monitoring

  # localhost:9090/targets for scrape debugging.
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      # target should be the :15692/metrics rabbit port and uri
      - ../../volumes/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"     # Prometheus web UI
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"     # Grafana web UI
    networks:
      - monitoring
    depends_on:
      - prometheus

volumes:
  grafana-data:

networks:
  monitoring:
    driver: bridge
