version: '3'
services:
  salt-master:
    image: localhost/salt/base:3
    container_name: salt
    volumes:
      - salt-master-data:/etc/salt/master.d
      - volumes/srv/salt:/srv/salt/
    ports:
      - "4505:4505"
      - "4506:4506"
    environment:
      - MASTER=salt-master
    command: salt-master --log-file-level=debug
        # /bin/bash -c "
        # yum install -y salt-master;
        # echo 'master: salt-master' > /etc/salt/minion.d/master.conf;
        # salt-master --log-file-level=debug"

  salt-minion:
    image: localhost/salt/base:3
    container_name: salt-minion
    # command: echo 'salt-master salt' >> /etc/hosts ; salt-minion
    command: salt-minion
    volumes:
      - salt-minion-data:/etc/salt/minion.d
    environment:
      - MASTER=salt-master
    depends_on:
      - salt-master
volumes:
  salt-master-data:
  salt-minion-data:
